name = "PixilllCreate"
author = "Team PixilllCraft"
version = "1.0 Curseforge"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0df6ce4c47ab239b46c95dcb3ee6745e2ff6f61b736ccd60987d7b3fee53de18"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.235"
