name = "PixilllCreate"
author = "Team PixilllCraft"
version = "1.0 Curseforge"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b171978fc10e412a41a40983ec8cb119bc743721dbc6627f358b644ee4afebfb"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.235"
