name = "PixilllCreate"
author = "Team PixilllCraft"
version = "1.0 Curseforge"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "42c5e67bf56edd3c217b555a0bb63e134f334c1917e2ed7e80a7e956f8ff27e2"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.235"
